export class User{
    created_on:string;
    display_name:string;
    email:string;
    expiry_date:string;
    image:string;
    ismigrated:number;
    ispaid:number;
    login_id:string;
    login_type:string;
    old_password:string;
    old_user_id:string;
    password:string;
    phone:string;
    redirect_url:string;
    trxn_migrate:string;
    userid:number;
    autologin:string;
}